import {
  AdminUser,
  AnalyticsDay,
  ChildProfile,
  CommunityAlert,
  CommunityTip,
  GuardianUser,
  MissingReport,
  NotificationItem,
  PartnerNode,
  ResourceContact,
} from './types';

const now = Date.now();

const hours = (h: number) => new Date(now - h * 3600000).toISOString();
const days = (d: number) => new Date(now - d * 86400000).toISOString();

const ageFromDob = (dob: string) => {
  const d = new Date(dob);
  const diff = Date.now() - d.getTime();
  return Math.max(0, Math.floor(diff / (365.25 * 24 * 3600000)));
};

export const guardiansSeed: GuardianUser[] = [
  {
    id: 'guardian-1',
    role: 'guardian',
    fullName: 'Amara Nkomo',
    phone: '+27 71 234 5678',
    email: 'amara.nkomo@kimbalert.africa',
    nationalId: '123456/10/1',
    location: 'Johannesburg, South Africa',
    avatarUrl: 'https://picsum.photos/seed/guard1/300/300',
    joinedAt: days(120),
    childrenCount: 2,
    verified: true,
  },
  {
    id: 'guardian-2',
    role: 'guardian',
    fullName: 'Kwesi Mensah',
    phone: '+233 24 665 9011',
    email: 'kwesi.mensah@kimbalert.africa',
    nationalId: 'GHA-22901-11',
    location: 'Accra, Ghana',
    avatarUrl: 'https://picsum.photos/seed/guard2/300/300',
    joinedAt: days(85),
    childrenCount: 2,
    verified: true,
  },
  {
    id: 'guardian-3',
    role: 'guardian',
    fullName: 'Mariam Adebayo',
    phone: '+234 803 555 1008',
    email: 'm.adebayo@kimbalert.africa',
    nationalId: 'NG-44210-99',
    location: 'Lagos, Nigeria',
    avatarUrl: 'https://picsum.photos/seed/guard3/300/300',
    joinedAt: days(67),
    childrenCount: 1,
    verified: false,
  },
  {
    id: 'guardian-4',
    role: 'guardian',
    fullName: 'Aisha Kamau',
    phone: '+254 712 442 880',
    email: 'aisha.kamau@kimbalert.africa',
    nationalId: 'KE-77810-11',
    location: 'Nairobi, Kenya',
    avatarUrl: 'https://picsum.photos/seed/guard4/300/300',
    joinedAt: days(51),
    childrenCount: 1,
    verified: true,
  },
  {
    id: 'guardian-5',
    role: 'guardian',
    fullName: 'Thandi Mokoena',
    phone: '+27 71 900 3302',
    email: 'thandi.mokoena@kimbalert.africa',
    nationalId: 'ZA-10982-77',
    location: 'Johannesburg, South Africa',
    avatarUrl: 'https://picsum.photos/seed/guard5/300/300',
    joinedAt: days(35),
    childrenCount: 2,
    verified: true,
  },
];

export const adminsSeed: AdminUser[] = [
  {
    id: 'admin-1',
    role: 'admin',
    fullName: 'Daniel Mbewe',
    phone: '+27 82 111 7788',
    email: 'daniel@kimbalert.africa',
    joinedAt: days(400),
    permissions: ['alerts:manage', 'registry:read', 'partners:write', 'analytics:read'],
    online: true,
  },
  {
    id: 'admin-2',
    role: 'admin',
    fullName: 'Grace Akinyi',
    phone: '+254 700 432 111',
    email: 'grace@kimbalert.africa',
    joinedAt: days(310),
    permissions: ['alerts:manage', 'tips:verify', 'partners:write'],
    online: true,
  },
  {
    id: 'admin-3',
    role: 'admin',
    fullName: 'Kofi Addo',
    phone: '+233 20 883 0210',
    email: 'kofi@kimbalert.africa',
    joinedAt: days(290),
    permissions: ['alerts:manage', 'analytics:read'],
    online: false,
  },
  {
    id: 'admin-4',
    role: 'admin',
    fullName: 'Amina Bello',
    phone: '+234 814 000 4455',
    email: 'amina@kimbalert.africa',
    joinedAt: days(188),
    permissions: ['registry:read', 'users:verify'],
    online: true,
  },
  {
    id: 'admin-5',
    role: 'admin',
    fullName: 'Sipho Nkosi',
    phone: '+27 78 430 5532',
    email: 'sipho@kimbalert.africa',
    joinedAt: days(122),
    permissions: ['partners:write', 'alerts:manage'],
    online: false,
  },
];

const childSeedsRaw = [
  {
    id: 'child-1',
    guardianId: 'guardian-1',
    name: 'Amara Okafor',
    dob: '2018-05-02',
    gender: 'Female',
    photoUrls: ['https://picsum.photos/seed/ch1a/500/500', 'https://picsum.photos/seed/ch1b/500/500'],
    physicalDescription: 'Curly hair, small star bracelet on right wrist.',
    bloodType: 'O+',
    conditions: ['Asthma'],
    medications: ['Salbutamol inhaler'],
    allergies: ['Dust'],
    doctorPhone: '+27 11 712 1990',
    schoolName: 'Johannesburg Central School',
    safeZoneLabel: 'Braamfontein Route',
    address: 'Braamfontein, Johannesburg',
    lat: -26.1929,
    lng: 28.0316,
    languages: ['English', 'Swahili'],
    emergencyContacts: [
      { id: 'ec-1', name: 'Chidi Okafor', relation: 'Father', phone: '+234 803 111 5532' },
      { id: 'ec-2', name: 'Ifeoma Okafor', relation: 'Aunt', phone: '+234 803 848 2210' },
    ],
    qrBraceletId: 'KA-2026-AM-001',
    qrLinked: true,
    vaultScore: 98,
    createdAt: days(130),
    lastUpdated: days(2),
  },
  {
    id: 'child-2',
    guardianId: 'guardian-1',
    name: 'Kwame Okafor',
    dob: '2020-07-14',
    gender: 'Male',
    photoUrls: ['https://picsum.photos/seed/ch2a/500/500'],
    physicalDescription: 'Small scar on left cheek, short hair.',
    bloodType: 'A-',
    conditions: ['None'],
    medications: [],
    allergies: ['Peanuts'],
    doctorPhone: '+27 11 712 1991',
    schoolName: 'Rosebank Learning Academy',
    safeZoneLabel: 'Rosebank Route',
    address: 'Rosebank, Johannesburg',
    lat: -26.1464,
    lng: 28.0413,
    languages: ['English'],
    emergencyContacts: [{ id: 'ec-3', name: 'Chidi Okafor', relation: 'Father', phone: '+234 803 111 5532' }],
    qrBraceletId: 'KA-2026-KW-008',
    qrLinked: false,
    vaultScore: 74,
    createdAt: days(94),
    lastUpdated: days(6),
  },
  {
    id: 'child-3',
    guardianId: 'guardian-2',
    name: 'Zainab Abba',
    dob: '2016-03-11',
    gender: 'Female',
    photoUrls: ['https://picsum.photos/seed/ch3a/500/500', 'https://picsum.photos/seed/ch3b/500/500'],
    physicalDescription: 'Braided hair with blue beads.',
    bloodType: 'B+',
    conditions: ['Wears reading glasses'],
    medications: [],
    allergies: [],
    schoolName: 'Accra Sunrise School',
    safeZoneLabel: 'Osu Safe Zone',
    address: 'Osu, Accra',
    lat: 5.55,
    lng: -0.2,
    languages: ['English', 'Hausa'],
    emergencyContacts: [{ id: 'ec-4', name: 'Fatima Abba', relation: 'Mother', phone: '+233 26 201 9911' }],
    qrBraceletId: 'KA-2026-ZA-004',
    qrLinked: true,
    vaultScore: 96,
    createdAt: days(210),
    lastUpdated: days(5),
  },
  {
    id: 'child-4',
    guardianId: 'guardian-2',
    name: 'Tayo Mensah',
    dob: '2015-10-01',
    gender: 'Male',
    photoUrls: ['https://picsum.photos/seed/ch4a/500/500'],
    physicalDescription: 'Tall for age, wears navy cap.',
    bloodType: 'AB+',
    conditions: ['None'],
    medications: [],
    allergies: ['Penicillin'],
    schoolName: 'Accra Primary',
    safeZoneLabel: 'Airport District',
    address: 'Airport City, Accra',
    lat: 5.61,
    lng: -0.17,
    languages: ['English', 'Twi'],
    emergencyContacts: [{ id: 'ec-5', name: 'Kwesi Mensah', relation: 'Father', phone: '+233 24 665 9011' }],
    qrBraceletId: 'KA-2026-TY-017',
    qrLinked: true,
    vaultScore: 88,
    createdAt: days(188),
    lastUpdated: days(11),
  },
  {
    id: 'child-5',
    guardianId: 'guardian-3',
    name: 'Ayo Adebayo',
    dob: '2019-08-23',
    gender: 'Male',
    photoUrls: ['https://picsum.photos/seed/ch5a/500/500'],
    physicalDescription: 'Short afro, green sneakers.',
    bloodType: 'O-',
    conditions: ['Mild eczema'],
    medications: ['Moisturizing cream'],
    allergies: ['Seafood'],
    schoolName: 'Lagos Island Learning Center',
    safeZoneLabel: 'Marina Route',
    address: 'Lagos Island',
    lat: 6.45,
    lng: 3.39,
    languages: ['English', 'Yoruba'],
    emergencyContacts: [{ id: 'ec-6', name: 'Mariam Adebayo', relation: 'Mother', phone: '+234 803 555 1008' }],
    qrBraceletId: 'KA-2026-AY-029',
    qrLinked: false,
    vaultScore: 61,
    createdAt: days(61),
    lastUpdated: days(18),
  },
  {
    id: 'child-6',
    guardianId: 'guardian-4',
    name: 'Nia Kamau',
    dob: '2017-01-19',
    gender: 'Female',
    photoUrls: ['https://picsum.photos/seed/ch6a/500/500'],
    physicalDescription: 'Dimples, yellow backpack.',
    bloodType: 'A+',
    conditions: ['None'],
    medications: [],
    allergies: [],
    schoolName: 'Nairobi Hills School',
    safeZoneLabel: 'Kilimani Ring',
    address: 'Kilimani, Nairobi',
    lat: -1.299,
    lng: 36.79,
    languages: ['English', 'Swahili'],
    emergencyContacts: [{ id: 'ec-7', name: 'Aisha Kamau', relation: 'Mother', phone: '+254 712 442 880' }],
    qrBraceletId: 'KA-2026-NI-021',
    qrLinked: true,
    vaultScore: 92,
    createdAt: days(79),
    lastUpdated: days(1),
  },
  {
    id: 'child-7',
    guardianId: 'guardian-5',
    name: 'Lerato Mokoena',
    dob: '2014-12-01',
    gender: 'Female',
    photoUrls: ['https://picsum.photos/seed/ch7a/500/500'],
    physicalDescription: 'Wears red hair clips.',
    bloodType: 'B-',
    conditions: ['None'],
    medications: [],
    allergies: [],
    schoolName: 'Johannesburg North',
    safeZoneLabel: 'Sandton Axis',
    address: 'Sandton, Johannesburg',
    lat: -26.107,
    lng: 28.056,
    languages: ['English', 'Zulu'],
    emergencyContacts: [{ id: 'ec-8', name: 'Thandi Mokoena', relation: 'Mother', phone: '+27 71 900 3302' }],
    qrBraceletId: 'KA-2026-LE-006',
    qrLinked: true,
    vaultScore: 83,
    createdAt: days(57),
    lastUpdated: days(3),
  },
  {
    id: 'child-8',
    guardianId: 'guardian-5',
    name: 'Sipho Mokoena Jr',
    dob: '2021-09-12',
    gender: 'Male',
    photoUrls: ['https://picsum.photos/seed/ch8a/500/500'],
    physicalDescription: 'Curly hair, blue raincoat.',
    bloodType: 'AB-',
    conditions: ['None'],
    medications: [],
    allergies: ['Pollen'],
    schoolName: 'Tiny Tots Sandton',
    safeZoneLabel: 'Rivonia Route',
    address: 'Rivonia, Johannesburg',
    lat: -26.058,
    lng: 28.059,
    languages: ['English'],
    emergencyContacts: [{ id: 'ec-9', name: 'Thandi Mokoena', relation: 'Mother', phone: '+27 71 900 3302' }],
    qrBraceletId: 'KA-2026-SJ-112',
    qrLinked: false,
    vaultScore: 52,
    createdAt: days(30),
    lastUpdated: days(10),
  },
];

export const childrenSeed: ChildProfile[] = childSeedsRaw.map((child) => ({
  ...child,
  age: ageFromDob(child.dob),
  medical: {
    bloodType: child.bloodType,
    conditions: [...child.conditions],
    medications: [...child.medications],
    allergies: [...child.allergies],
    doctorPhone: child.doctorPhone,
  },
  location: {
    schoolName: child.schoolName,
    safeZoneLabel: child.safeZoneLabel,
    address: child.address,
    lat: child.lat,
    lng: child.lng,
  },
}));

export const reportsSeed: MissingReport[] = [
  {
    id: 'report-1',
    childId: 'child-1',
    guardianId: 'guardian-1',
    status: 'active',
    priority: 'high',
    startedAt: hours(2),
    lastSeenLocation: {
      address: 'Johannesburg Park Station North Entrance',
      lat: -26.2044,
      lng: 28.0446,
    },
    lastSeenAt: hours(3),
    outfit: 'Yellow sweater, white sneakers',
    context: 'Child separated during evening rush.',
    whoNearby: 'Older woman, blue scarf',
    withKnownPerson: false,
    anonymousReport: false,
    currentRadiusKm: 15,
    expansionRateKmPerHour: 5,
    notifiedCount: 2840,
    tipsReceived: 3,
    partnerNotified: {
      police: true,
      hospital: true,
      school: true,
      media: false,
      community: true,
    },
    timeline: [
      { id: 'tl-1', timestamp: hours(2.8), title: 'Report Submitted', detail: 'Guardian activated flare.', severity: 'warning', actor: 'Guardian' },
      { id: 'tl-2', timestamp: hours(2.4), title: 'Admin Confirmed', detail: 'Command center verified report.', severity: 'success', actor: 'Admin Daniel' },
      { id: 'tl-3', timestamp: hours(1.4), title: 'Radius Expanded', detail: 'Expanded from 10km to 15km.', severity: 'info', actor: 'System' },
    ],
    assignedAdminId: 'admin-1',
    caseNotes: ['Police patrol deployed to market corridor.'],
  },
  {
    id: 'report-2',
    childId: 'child-2',
    guardianId: 'guardian-1',
    status: 'pending',
    priority: 'medium',
    startedAt: hours(0.3),
    lastSeenLocation: {
      address: 'Rosebank Taxi Rank',
      lat: -26.1469,
      lng: 28.0424,
    },
    lastSeenAt: hours(0.5),
    outfit: 'Blue t-shirt, denim shorts',
    context: 'Lost visual contact at bus station.',
    whoNearby: 'Bus conductor and commuters',
    withKnownPerson: false,
    anonymousReport: false,
    currentRadiusKm: 10,
    expansionRateKmPerHour: 5,
    notifiedCount: 420,
    tipsReceived: 0,
    partnerNotified: {
      police: false,
      hospital: false,
      school: false,
      media: false,
      community: true,
    },
    timeline: [{ id: 'tl-4', timestamp: hours(0.3), title: 'Pending Verification', detail: 'Waiting for operator validation.', severity: 'info', actor: 'System' }],
    assignedAdminId: 'admin-2',
    caseNotes: ['Need callback with guardian for photo clarity.'],
  },
  {
    id: 'report-3',
    childId: 'child-3',
    guardianId: 'guardian-2',
    status: 'found',
    priority: 'critical',
    startedAt: hours(11),
    closedAt: hours(5.5),
    lastSeenLocation: {
      address: 'Lagos Island Junction',
      lat: 6.4474,
      lng: 3.3903,
    },
    lastSeenAt: hours(12),
    outfit: 'School uniform',
    context: 'Child missed school pickup point.',
    withKnownPerson: true,
    knownPersonDetails: 'Unknown male wearing delivery uniform',
    anonymousReport: false,
    currentRadiusKm: 20,
    expansionRateKmPerHour: 5,
    notifiedCount: 5190,
    tipsReceived: 5,
    partnerNotified: {
      police: true,
      hospital: true,
      school: true,
      media: true,
      community: true,
    },
    timeline: [
      { id: 'tl-5', timestamp: hours(10.8), title: 'Flare Activated', detail: '10km emergency notification launched.', severity: 'warning', actor: 'Admin Grace' },
      { id: 'tl-6', timestamp: hours(8.2), title: 'Credible Tip', detail: 'Community tip matched child appearance.', severity: 'success', actor: 'Tip Desk' },
      { id: 'tl-7', timestamp: hours(5.5), title: 'Child Found Safe', detail: 'Child safely reunited with guardian.', severity: 'success', actor: 'Admin Daniel' },
    ],
    assignedAdminId: 'admin-1',
    caseNotes: ['Case concluded after verified tip.'],
    resolutionType: 'found_safe',
  },
  {
    id: 'report-4',
    childId: 'child-6',
    guardianId: 'guardian-4',
    status: 'closed',
    priority: 'low',
    startedAt: days(4),
    closedAt: days(3.8),
    lastSeenLocation: {
      address: 'Kilimani Street 9',
      lat: -1.29,
      lng: 36.79,
    },
    lastSeenAt: days(4),
    outfit: 'Sports kit',
    context: 'False alarm, child with neighbor.',
    whoNearby: 'Neighbor family',
    withKnownPerson: true,
    knownPersonDetails: 'Neighbor parent',
    anonymousReport: false,
    currentRadiusKm: 10,
    expansionRateKmPerHour: 5,
    notifiedCount: 610,
    tipsReceived: 1,
    partnerNotified: {
      police: false,
      hospital: false,
      school: false,
      media: false,
      community: true,
    },
    timeline: [
      { id: 'tl-8', timestamp: days(4), title: 'Report Submitted', detail: 'Guardian triggered emergency report.', severity: 'warning', actor: 'Guardian' },
      { id: 'tl-9', timestamp: days(3.8), title: 'Case Retracted', detail: 'Guardian confirmed child safe with neighbor.', severity: 'info', actor: 'Guardian' },
    ],
    assignedAdminId: 'admin-4',
    caseNotes: ['Confirmed as guardian retraction.'],
    resolutionType: 'guardian_retracted',
  },
];

export const tipsSeed: CommunityTip[] = [
  { id: 'tip-1', reportId: 'report-1', createdAt: hours(1.8), reporterName: 'Community Member', description: 'Saw child near central bus lane.', location: 'Park Station Bus Lane', when: hours(2), status: 'pending' },
  { id: 'tip-2', reportId: 'report-1', createdAt: hours(1.3), reporterName: 'Community Member', description: 'Possible sighting at market arcade.', location: 'Braamfontein Arcade', when: hours(1.5), status: 'credible' },
  { id: 'tip-3', reportId: 'report-1', createdAt: hours(1.1), reporterName: 'Community Member', description: 'Taxi driver saw matching child.', location: 'Ring Road', when: hours(1.2), status: 'investigate' },
  { id: 'tip-4', reportId: 'report-2', createdAt: hours(0.2), reporterName: 'Community Member', description: 'No clear photo match.', location: 'Westlands Stop', when: hours(0.2), status: 'dismissed', dismissReason: 'Insufficient evidence' },
  { id: 'tip-5', reportId: 'report-3', createdAt: hours(9.1), reporterName: 'Community Member', description: 'Child spotted at water kiosk.', location: 'Lagos Block C', when: hours(9.1), status: 'credible' },
  { id: 'tip-6', reportId: 'report-3', createdAt: hours(8.7), reporterName: 'Community Member', description: 'Companion description matches previous tip.', location: 'Lagos Marina', when: hours(8.7), status: 'credible' },
  { id: 'tip-7', reportId: 'report-3', createdAt: hours(7.4), reporterName: 'Community Member', description: 'Security guard provided direction.', location: 'Kiosk Lane', when: hours(7.4), status: 'credible' },
  { id: 'tip-8', reportId: 'report-4', createdAt: days(4), reporterName: 'Community Member', description: 'Child seen with known family.', location: 'Kilimani Street 9', when: days(4), status: 'credible' },
];

export const communityAlertsSeed: CommunityAlert[] = [
  { id: 'ca-1', reportId: 'report-1', firstName: 'Amara', age: 7, distanceKm: 2.5, location: 'Johannesburg Park Station', lastSeenAt: hours(2), status: 'active', radiusKm: 15, notifiedCount: 2840, blurredPhotoUrl: 'https://picsum.photos/seed/blur1/120/120' },
  { id: 'ca-2', reportId: 'report-2', firstName: 'Kwame', age: 5, distanceKm: 4.1, location: 'Rosebank Taxi Rank', lastSeenAt: hours(0.4), status: 'pending', radiusKm: 10, notifiedCount: 420, blurredPhotoUrl: 'https://picsum.photos/seed/blur2/120/120' },
  { id: 'ca-3', reportId: 'report-3', firstName: 'Zainab', age: 9, distanceKm: 6.8, location: 'Lagos Island', lastSeenAt: hours(10), status: 'found', radiusKm: 20, notifiedCount: 5190 },
  { id: 'ca-4', reportId: 'report-10', firstName: 'Lerato', age: 11, distanceKm: 8.7, location: 'Sandton District', lastSeenAt: hours(5), status: 'active', radiusKm: 10, notifiedCount: 1220, blurredPhotoUrl: 'https://picsum.photos/seed/blur4/120/120' },
  { id: 'ca-5', reportId: 'report-11', firstName: 'Tayo', age: 10, distanceKm: 11.3, location: 'Accra Mall', lastSeenAt: hours(7), status: 'active', radiusKm: 15, notifiedCount: 2010, blurredPhotoUrl: 'https://picsum.photos/seed/blur5/120/120' },
  { id: 'ca-6', reportId: 'report-12', firstName: 'Nia', age: 8, distanceKm: 3.2, location: 'Kilimani', lastSeenAt: hours(12), status: 'closed', radiusKm: 10, notifiedCount: 940 },
];

export const resourcesSeed: ResourceContact[] = [
  { id: 'rc-1', type: 'police', name: 'Central Police Station', phone: '+254 700 123 456', address: 'Nairobi CBD', lat: -1.283, lng: 36.82 },
  { id: 'rc-2', type: 'police', name: 'Kilimani Police', phone: '+254 700 234 567', address: 'Kilimani', lat: -1.298, lng: 36.79 },
  { id: 'rc-3', type: 'police', name: 'Westlands Police', phone: '+254 700 345 678', address: 'Westlands', lat: -1.266, lng: 36.81 },
  { id: 'rc-4', type: 'police', name: 'Makadara Police', phone: '+254 700 456 789', address: 'Makadara', lat: -1.304, lng: 36.86 },
  { id: 'rc-5', type: 'hospital', name: 'Nairobi City Hospital', phone: '+254 711 220 100', address: 'Nairobi', lat: -1.29, lng: 36.815 },
  { id: 'rc-6', type: 'hospital', name: 'Kenyatta Emergency Wing', phone: '+254 711 221 100', address: 'Upper Hill', lat: -1.304, lng: 36.815 },
  { id: 'rc-7', type: 'hospital', name: 'Westlands Pediatric Center', phone: '+254 711 222 100', address: 'Westlands', lat: -1.267, lng: 36.808 },
  { id: 'rc-8', type: 'hospital', name: 'Aga Khan Emergency', phone: '+254 711 223 100', address: 'Parklands', lat: -1.261, lng: 36.817 },
  { id: 'rc-9', type: 'school', name: 'Central International School', phone: '+254 733 100 200', address: 'CBD', lat: -1.287, lng: 36.816 },
  { id: 'rc-10', type: 'school', name: 'Nairobi Primary School', phone: '+254 733 100 201', address: 'Westlands', lat: -1.272, lng: 36.81 },
  { id: 'rc-11', type: 'school', name: 'Kilimani Junior School', phone: '+254 733 100 202', address: 'Kilimani', lat: -1.296, lng: 36.79 },
  { id: 'rc-12', type: 'school', name: 'Parklands Academy', phone: '+254 733 100 203', address: 'Parklands', lat: -1.259, lng: 36.818 },
];

export const partnersSeed: PartnerNode[] = [
  { id: 'pn-1', name: 'Central Police Station', type: 'police', contactPhone: '+254 700 123 456', location: 'Nairobi CBD', active: true, lastNotifiedAt: hours(2), notificationHistory: [hours(2), hours(6)] },
  { id: 'pn-2', name: 'Kilimani Division', type: 'police', contactPhone: '+254 722 987 654', location: 'Kilimani', active: true, lastNotifiedAt: hours(8), notificationHistory: [hours(8), days(2)] },
  { id: 'pn-3', name: 'Aga Khan Emergency', type: 'hospital', contactPhone: '+254 711 009 000', location: 'Parklands', active: true, lastNotifiedAt: days(1), notificationHistory: [days(1)] },
  { id: 'pn-4', name: 'City Clinic South B', type: 'hospital', contactPhone: '+254 720 000 000', location: 'South B', active: false, lastNotifiedAt: days(33), notificationHistory: [days(33)] },
  { id: 'pn-5', name: 'Nairobi Primary School', type: 'school', contactPhone: '+254 733 456 769', location: 'Processional Way', active: true, lastNotifiedAt: hours(20), notificationHistory: [hours(20), days(4)] },
  { id: 'pn-6', name: 'Kilimani Junior School', type: 'school', contactPhone: '+254 733 456 770', location: 'Kilimani', active: true, lastNotifiedAt: days(3), notificationHistory: [days(3)] },
  { id: 'pn-7', name: 'Metro FM Nairobi', type: 'media', contactPhone: '+254 755 567 444', location: 'Upper Hill', active: true, lastNotifiedAt: days(6), notificationHistory: [days(6)] },
  { id: 'pn-8', name: 'Community Watch Network', type: 'community', contactPhone: '+254 799 888 222', location: 'Nairobi Metro', active: true, lastNotifiedAt: hours(5), notificationHistory: [hours(5), days(1)] },
];

export const notificationsSeed: NotificationItem[] = [
  { id: 'n-1', userId: 'guardian-1', title: 'Alert verified', body: 'Command Center activated your flare.', type: 'success', createdAt: hours(1.9), read: false, route: '/guardian/alert/status/report-1' },
  { id: 'n-2', userId: 'guardian-1', title: 'Radius expanded', body: 'Search radius is now 15km.', type: 'info', createdAt: hours(1.2), read: false, route: '/guardian/alert/status/report-1' },
  { id: 'n-3', userId: 'guardian-1', title: 'Tip received', body: 'A community member submitted a tip.', type: 'warning', createdAt: hours(1.1), read: false, route: '/guardian/activity' },
  { id: 'n-4', userId: 'guardian-1', title: 'SMS sent', body: '2,840 community members notified.', type: 'success', createdAt: hours(1), read: true },
  { id: 'n-5', userId: 'guardian-1', title: 'Safety drill reminder', body: 'Monthly drill starts tomorrow at 10:00.', type: 'info', createdAt: days(1), read: true },
  { id: 'n-6', userId: 'guardian-1', title: 'Profile completion', body: 'Link a QR bracelet to boost safety score.', type: 'warning', createdAt: days(2), read: true, route: '/guardian/children' },
  { id: 'n-7', userId: 'guardian-1', title: 'Community update', body: 'New police station node is now active.', type: 'info', createdAt: days(3), read: true },
  { id: 'n-8', userId: 'guardian-1', title: 'Report closed', body: 'A previous alert was resolved successfully.', type: 'success', createdAt: days(4), read: true, route: '/guardian/activity/history' },
  { id: 'n-9', userId: 'guardian-1', title: 'Network test', body: 'Push + SMS channels are operational.', type: 'success', createdAt: days(5), read: true },
  { id: 'n-10', userId: 'guardian-1', title: 'Emergency contact', body: 'Update your trusted contacts list.', type: 'warning', createdAt: days(6), read: false, route: '/guardian/profile' },
  { id: 'n-11', userId: 'admin-1', title: 'Critical case assigned', body: 'Report-1 assigned to you.', type: 'error', createdAt: hours(2), read: false, route: '/admin/alerts/report-1' },
  { id: 'n-12', userId: 'admin-1', title: 'Tip waiting review', body: '3 pending tips require verification.', type: 'warning', createdAt: hours(1.5), read: false, route: '/admin/alerts' },
  { id: 'n-13', userId: 'admin-1', title: 'Partner offline', body: 'City Clinic South B has not acknowledged in 30 days.', type: 'warning', createdAt: days(1), read: true, route: '/admin/partners' },
  { id: 'n-14', userId: 'admin-1', title: 'System health', body: 'SMS gateway is healthy.', type: 'success', createdAt: days(2), read: true },
  { id: 'n-15', userId: 'admin-1', title: 'Daily summary', body: '4 alerts today, 2 resolved.', type: 'info', createdAt: days(1), read: true, route: '/admin/dashboard' },
];

export const analyticsSeed: AnalyticsDay[] = [
  { date: '2026-02-18', alerts: 4, avgResponseMins: 7.2, found: 3, falseReports: 0, open: 1, pushSent: 1820, smsSent: 1310 },
  { date: '2026-02-19', alerts: 3, avgResponseMins: 6.1, found: 2, falseReports: 0, open: 1, pushSent: 1625, smsSent: 1204 },
  { date: '2026-02-20', alerts: 6, avgResponseMins: 9.3, found: 4, falseReports: 1, open: 1, pushSent: 2381, smsSent: 1802 },
  { date: '2026-02-21', alerts: 5, avgResponseMins: 8.4, found: 3, falseReports: 0, open: 2, pushSent: 2110, smsSent: 1710 },
  { date: '2026-02-22', alerts: 2, avgResponseMins: 5.8, found: 2, falseReports: 0, open: 0, pushSent: 1088, smsSent: 880 },
  { date: '2026-02-23', alerts: 7, avgResponseMins: 10.2, found: 4, falseReports: 1, open: 2, pushSent: 3020, smsSent: 2411 },
  { date: '2026-02-24', alerts: 4, avgResponseMins: 7.4, found: 2, falseReports: 0, open: 2, pushSent: 1890, smsSent: 1450 },
];
